services:
  pymap.lan:
    build:
      context: Dockerfiles/email-server
      args:
        - HOSTNAME=pymap.lan
      dockerfile: Dockerfile.mail
    hostname: pymap.lan
    domainname: pymap.lan
    ports:
      - "25:25"   # SMTP
      - "587:587" # SMTP submission
      - "143:143" # IMAP
    networks:
      - mailnet

  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=pymap.lan
      - ROUNDCUBEMAIL_SMTP_SERVER=smtp://pymap.lan
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    ports:
      - "8080:80"
    volumes:
      - roundcube_mail:/var/www/html
    networks:
      - mailnet

networks:
  mailnet:
    driver: bridge

volumes:
  roundcube_mail:
  server_data: