version: '0.0.1'
services:
  kali:
    entrypoint: ['bash']
    tty: true
    build: ./dockers/kali/Dockerfile
    ports:
     - "5902:5902"
  mail1:
    image: "roundcube/roundcubemail"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_DEFAULT_HOST=localhost
      - ROUNDCUBEMAIL_SMTP_SERVER=localhost
    ports:
      - 80:8081
      - 143:143
  mail2:
    image: "roundcube/roundcubemail"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_PORT=144
      - ROUNDCUBEMAIL_DEFAULT_HOST=localhost
      - ROUNDCUBEMAIL_SMTP_SERVER=localhost
    ports:
      - 80:8082
      - 144:144
  ubuntu20:
    entrypoint: ['bash']
    tty: true
    build:
      context: ./
      dockerfile: ./dockers/ubuntu20.04/Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
      - "6379:6379"
    environment:
      - FLASK_ENV="development"
      - NVM_DIR="/home/pymap"
  alpine:
    entrypoint: ['bash']
    tty: true
    build: ./dockers/alpine/Dockerfile