services:
  pymap-aio:
    hostname: pymap.lan
    build:
      context: .
      dockerfile: Dockerfiles/aio/Dockerfile
      args:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_HOST
        - POSTGRES_PORT
        - DJANGO_ENV
        - DJANGO_SETTINGS_MODULE
        - CELERY_BROKER_URL
        - CELERY_RESULT_BACKEND
        - STATIC_ROOT
        - PYMAP_LOGDIR
        - SECRET_KEY
    ports:
      - "80:80"
    volumes:
      - aio_pgdata:/var/lib/postgresql/data

volumes:
  aio_pgdata:
