version: '3'

services:
  redis:
    image: "docker.io/library/redis:latest"
    ports:
      - "6379:6379"
    restart: always

  aio:
    build:
      context: .
      dockerfile: Dockerfiles/aio/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=pymap.settings
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfiles/celery/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./src:/app
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=pymap.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  django-app:
    build:
      context: .
      dockerfile: Dockerfiles/django/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery-worker
    volumes:
      - ./src:/app
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=pymap.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  email-server:
    build:
      context: Dockerfiles/email-server
      dockerfile: Dockerfile
    networks:
      - mail
    ports:
      - "2500:2500"
      - "1430:1430"
      - "4650:4650"
      - "9930:9930"

  rainloop:
    build:
      context: Dockerfiles/rainloop
      dockerfile: Dockerfile
    networks:
      - mail
    ports:
      - "8080:8080"
    depends_on:
      - email-server


networks:
  mail:
    driver: bridge