services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pymap.lan}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-PGAdmin}
    ports:
      - 9001:80
  
  rinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 5540:5540