services:
  mailserver:
    build:
      context: Dockerfiles/email-server
      dockerfile: Dockerfile
    container_name: mailserver
    hostname: mail
    domainname: pymap.internal
    ports:
      - "25:25"   # SMTP
      - "587:587" # SMTP submission
      - "143:143" # IMAP
    environment:
      - MAIL_DOMAIN=pymap.internal
      - MAIL_RELAY_HOST=mail.pymap.internal
      - DOVECOT_DISABLE_SSL=1
    volumes:
      - ./data:/data
      - ./config:/etc/postfix
      - ./dovecot:/etc/dovecot
    networks:
      - mailnet

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "8080:80"
    volumes:
      - ./roundcube/config:/var/www/html/config
      - ./roundcube/mail:/var/www/html/mail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail.pymap.internal
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=mail.pymap.internal
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_SMTP_USER=pymin@pymap.internal
      - ROUNDCUBEMAIL_SMTP_PASS="changeme!"

networks:
  mailnet:
    driver: bridge
