services:
  redis:
    image: "docker.io/library/redis:latest"
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: "docker.io/library/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pymap}
      POSTGRES_USER: ${POSTGRES_USER:-pymap}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_HOST: ${POSTGRES_HOST:-127.0.0.1}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pymap-aio:
    hostname: pymap.lan
    build:
      context: .
      dockerfile: Dockerfiles/aio/Dockerfile
      args:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_HOST
        - POSTGRES_PORT
        - DJANGO_ENV
        - DJANGO_SETTINGS_MODULE
        - CELERY_BROKER_URL
        - CELERY_RESULT_BACKEND
        - STATIC_ROOT
        - LOGDIR
        - SECRET_KEY
    ports:
      - "80:80"
    volumes:
      - ./src:/app
      - aio_pgdata:/var/lib/postgresql/data

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfiles/celery/Dockerfile
      args:
        - DJANGO_ENV
        - DJANGO_SETTINGS_MODULE
        - CELERY_BROKER_URL
        - CELERY_RESULT_BACKEND
    depends_on:
      - redis
    volumes:
      - shared_logs:/var/log/pymap

  pymap:
    build:
      context: .
      dockerfile: Dockerfiles/django/Dockerfile
      args:
        - DJANGO_ENV
        - DJANGO_SETTINGS_MODULE
        - CELERY_BROKER_URL
        - CELERY_RESULT_BACKEND
        - STATIC_ROOT
        - LOGDIR
        - SECRET_KEY
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery-worker
      - postgres
    volumes:
      - shared_logs:/var/log/pymap

  email-server:
    build:
      context: Dockerfiles/email-server
      dockerfile: Dockerfile
    networks:
      - mail
    ports:
      - "2500:2500"
      - "1430:1430"
      - "4650:4650"
      - "9930:9930"

  rainloop:
    build:
      context: Dockerfiles/rainloop
      dockerfile: Dockerfile
    networks:
      - mail
    ports:
      - "8080:8080"
    depends_on:
      - email-server
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


networks:
  mail:
    driver: bridge

volumes:
  shared_logs:
  pgdata:
  aio_pgdata: