services:
  pymap.internal:
    build:
      context: Dockerfiles/email-server
      dockerfile: Dockerfile.mail
    hostname: pymap.internal
    domainname: pymap.internal
    ports:
      - "25:25"   # SMTP
      - "587:587" # SMTP submission
      - "143:143" # IMAP
    environment:
      - MAIL_DOMAIN=pymap.internal
      - MAIL_RELAY_HOST=mail.pymap.internal
      - DOVECOT_DISABLE_SSL=1
    volumes:
      - server_data:/data
    networks:
      - mailnet

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "8080:80"
    volumes:
      - roundcube_mail:/var/www/html/mail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=pymap.internal
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=pymap.internal
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_SMTP_USER=test@pymap.internal
      - ROUNDCUBEMAIL_SMTP_PASS=Password123
    networks:
      - mailnet

networks:
  mailnet:
    driver: bridge

volumes:
  roundcube_mail:
  server_data: