"""empty message

Revision ID: 1f0719a035e4
Revises: e3c75452aa15
Create Date: 2023-01-30 16:50:12.873670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0719a035e4'
down_revision = 'e3c75452aa15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_celery_task_owner_id_user'), 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_celery_task_owner_id_user'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
