"""empty message

Revision ID: 462b94f418fc
Revises: b5d2315abbfa
Create Date: 2023-01-30 20:01:48.248106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462b94f418fc'
down_revision = 'b5d2315abbfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_username', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_celery_task_owner_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_celery_task_owner_username_user'), 'user', ['owner_username'], ['username'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_celery_task_owner_username_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_celery_task_owner_id_user', 'user', ['owner_id'], ['id'])
        batch_op.drop_column('owner_username')

    # ### end Alembic commands ###
