"""empty message

Revision ID: 51acde7d55ea
Revises: 462b94f418fc
Create Date: 2023-02-04 18:16:49.349039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51acde7d55ea'
down_revision = '462b94f418fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
