"""empty message

Revision ID: 90cc6dc4c93d
Revises: 51acde7d55ea
Create Date: 2023-02-26 19:10:32.460134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cc6dc4c93d'
down_revision = '51acde7d55ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.drop_column('domain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
