version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dmns
      WORDPRESS_DB_PASSWORD: dmns
      WORDPRESS_DB_NAME: wp1
    volumes:
      - wordpress_local:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wp1
      MYSQL_USER: dmns
      MYSQL_PASSWORD: dmns
      MYSQL_ROOT_PASSWORD: 'gDRI57Pr3mLyGNCe49OJ'
    volumes:
      - wp_db:/var/lib/mysql
      - wp_db_home:/home

volumes:
  wordpress_local:
  wp_db:
  wp_db_home: