# Generated by Django 5.2.14 on 2026-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pymap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrationtask",
            name="exit_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
