#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
	CREATE USER ${CELERY_POSTGRES_USER} WITH ENCRYPTED PASSWORD '${CELERY_POSTGRES_PASSWORD}';
	CREATE DATABASE ${CELERY_POSTGRES_DB};
	GRANT ALL PRIVILEGES ON DATABASE ${CELERY_POSTGRES_DB} TO ${CELERY_POSTGRES_USER};
EOSQL