[tool.poetry]
name = "pymap"
version = "2.4.0"
description = ""
authors = ["hallowslab <hallow.tech.lab@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = ">=2.0.1"
redis = "^4.1.4"
gunicorn = "^20.1.0"
Flask-SQLAlchemy = "^2.5.1"
celery = {extras = ["eventlet"], version = "^5.2.7"}
Flask-Cors = "^3.0.10"
flask-praetorian = "^1.4.0"
Flask-Migrate = "^4.0.0"

[tool.black]
extend-exclude = "^/migrations"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^6.2.5"
taskipy = "^1.8.0"
mypy = "^0.910"
autoflake = "^1.4"
coverage = "^6.3.2"
Flask-Testing = "^0.8.1"
types-redis = "^4.3.21"

[tool.taskipy.tasks]
clientDev = "cd client && npm start"
prod = "cd client && npm run build && cd .. && gunicorn -w 4 -b 0.0.0.0:5000 'server:create_flask_app()'"
worker = "celery -A server.tasks worker -E --pool=eventlet --concurrency=100 -l INFO"
workerDev = "celery -A server.tasks worker -E --pool=eventlet --concurrency=100 -l DEBUG"
workerWin = "celery -A server.tasks worker -E --pool=solo -l DEBUG"
apiDev = "flask --app manage --debug run -h 0.0.0.0 "
### Database commands
# Prod
initDB = "flask --app manage db init"
createDB = "flask --app manage create-db"
addAdmin = "flask --app manage create-admin admin CHANGE_ME"
# Upgrading
upgradeDB = "flask --app manage db upgrade && flask --app manage --debug db upgrade"
# Dev
# migrate needs to be run before update in a dev environment
migrateDB = "flask --app manage db migrate"
createDevDB = "flask --app manage --debug create-db"
addDevAdmin = "flask --app manage --debug create-admin admin CHANGE_ME"
### Misc
genLogs = "python scripts/generate_random_logs.py"
buildDeps = "python scripts/build_client_dependencies_cache.py"
### Formatting, tests & coverage
format = "black . && autoflake -i -r  --remove-unused-variables --remove-all-unused-imports --exclude client,migrations . && mypy core server"
testCore = "pytest tests/core"
testServer = "pytest tests/server"
testBackend = "pytest tests/"
testClient = "cd client && npm test"
coverage = "coverage run -m pytest && coverage report"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
