[tool.poetry]
name = "pymap"
version = "0.1.0"
description = ""
authors = ["hallowslab <hallow.tech.lab@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^6.2.5"
taskipy = "^1.8.0"
mypy = "^0.910"
autoflake = "^1.4"
coverage = "^6.3.2"

[tool.taskipy.tasks]
runserver = "python manage.py runserver"
migrate = "python manage.py migrate"
### Formatting, tests & coverage
format = "black . && autoflake -i -r  --remove-unused-variables --remove-all-unused-imports core && mypy core"
testCore = "pytest tests/core"
coverage = "coverage run -m pytest && coverage report"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
