# Generated by Django 5.0.1 on 2024-01-12 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("log_path", models.CharField(max_length=255)),
                ("task_id", models.CharField(max_length=255)),
                ("n_accounts", models.IntegerField()),
                ("domains", models.CharField(blank=True, max_length=100, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("finished", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("run_time", models.IntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
