# Generated by Django 5.0.6 on 2024-06-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migrator", "0002_alter_celerytask_run_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celerytask",
            name="destination",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="celerytask",
            name="domains",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="celerytask",
            name="source",
            field=models.CharField(max_length=255),
        ),
    ]
