# Generated by Django 5.0.7 on 2024-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migrator", "0005_userpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="celerytask",
            name="terminated",
            field=models.BooleanField(default=False),
        ),
    ]
