"""
Django settings for pymap project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import json
import os
import errno
from pathlib import Path
import sys
from typing import Dict, List
from django.core.management.utils import get_random_secret_key
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import quote


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent
DJANGO_ENV: str = os.environ.get("DJANGO_ENV", "production")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = None

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = True if DJANGO_ENV == "development" else False

# Checks django is running in test mode
TESTING = "test" in sys.argv


if DEBUG:
    # We use print logging is not yet configured
    print(
        f"""WARNING: Debug is turned on, if running in production,
          change the value of the environment variable to production,
          current value: DJANGO_ENV={DJANGO_ENV}"""
    )

CONFIG_FILE = os.environ.get("DJANGO_CONFIG_FILE")
if not CONFIG_FILE:
    CONFIG_FILE = "config.json" if DJANGO_ENV == "production" else "config.dev.json"

ALLOWED_HOSTS: List[str] = []

CSRF_TRUSTED_ORIGINS: List[str] = []

# The Debug Toolbar is shown only if your IP address is listed in Django’s INTERNAL_IPS setting.
INTERNAL_IPS: List[str] = [
    # ...
    "127.0.0.1",
    "172.17.0.1",
    # ...
]

# Application definition

INSTALLED_APPS = [
    "migrator",
    "pymap",
    "django_celery_results",
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "migrator.middleware.require_auth.staff_only",
    "django.middleware.cache.FetchFromCacheMiddleware",
]

ROOT_URLCONF = "pymap.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pymap.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Cache
# https://docs.djangoproject.com/en/5.0/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://redis:6379/0",
    },
    "django-celery": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://redis:6379/1",
    },
}
CACHE_MIDDLEWARE_SECONDS = 3600
if DJANGO_ENV == "development":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
# TODO: consider adding internationalization
LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Lisbon"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.environ.get("STATIC_ROOT", Path(BASE_DIR, "static"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# This should match the name of your login URL pattern
# This setting specifies the URL where the user will be redirected
# if they are not authenticated and try to access a protected view.
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "sync/"

# Celery configuration
CELERY_BROKER_URL = None
CELERY_RESULT_BACKEND = "redis://redis:6379/2"
CELERY_CACHE_BACKEND = "django-celery"
CELERY_TIMEZONE = "Europe/Lisbon"
CELERY_TASK_TRACK_STARTED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# TODO: Check if this setting does not expose any data that it shouldn't
CELERY_RESULT_EXTENDED = True

# Initial logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Application's log directory

PYMAP_LOGDIR = "pymap_logs"

# Custom settings
PYMAP_SETTINGS: Dict[str, str] = {}


def load_custom_settings(config_path: str) -> dict:
    """
    Load custom settings from a json file, return data should be dictionary with key values

    Raises:
        ImproperlyConfigured: on missing config, if data is None before returning
    """

    config_file = Path(config_path)
    data = None

    if not config_file.is_file():
        raise ImproperlyConfigured(f"Config path provided {config_file} is not a file")

    with open(config_file) as f:
        try:
            data = json.load(f)
        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            raise ImproperlyConfigured(
                f"Failed to load json from config file: {config_file}, reason: {e}"
            )

    allowed_keys = [
        "PYMAP_LOGDIR",
        "HOSTS",
        "LOGGING",
        "DATABASES",
        "ALLOWED_HOSTS",
        "CSRF_TRUSTED_ORIGINS",
        "CACHES",
        "CACHE_MIDDLEWARE_SECONDS",
        "CELERY_BROKER_URL",
    ]

    for key in data:
        if key not in allowed_keys:
            print(
                f"Warning: {key} is not a recognized config key, this will not be loaded"
            )

    # Use dictionary comprehension to generate a new dataset
    print(f"Loaded data from: {config_file}")
    filtered_data = {key: value for key, value in data.items() if key in allowed_keys}

    if filtered_data is None:
        raise ImproperlyConfigured(
            f"Could not load data from config file: {config_file}"
        )

    return filtered_data


def build_broker_url(config: dict[str, str]) -> str:
    """
    Builds a string for the broker url from a dictionary
    """
    scheme = config.get("scheme", "amqp")
    username = quote(config["username"])
    password = quote(config["password"])
    host = config["host"]
    port = config.get("port", 5672)
    vhost = quote(config.get("vhost", "/"), safe="")
    return f"{scheme}://{username}:{password}@{host}:{port}/{vhost}"


def load_key_file(secret_path: str) -> str:
    """
    Load SECRET_KEY from file.

    Raises:
        ImproperlyConfigured: On missing file, failing to read the file, or length below 50.
    """

    secret_file = Path(secret_path)
    secret_key = None

    if not secret_file.is_file():
        raise ImproperlyConfigured(
            f"Secret key file not found at: {secret_file.resolve()}"
        )

    try:
        secret_key = secret_file.read_text(encoding="utf-8").strip()
    except OSError as e:
        raise ImproperlyConfigured(f"Error reading secret key file: {e}")

    if not secret_key:
        raise ImproperlyConfigured(f"Failed to load secret from: {secret_key}")

    if len(secret_key) < 50:
        raise ImproperlyConfigured(
            "SECRET_KEY is too short. Must be at least 50 characters."
        )

    return secret_key


def load_settings_env() -> None:
    """
    Load custom environment variables into global variables.

    This function loads specific environment variables into global variables if they are defined.
    The environment variables to be loaded are specified in the SETTINGS list.
    If any of these environment variables are found, they are assigned to the corresponding
    global variables in the current namespace.

    Returns:
        None
    """
    global ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS
    SETTINGS = [
        "CELERY_RESULT_BACKEND",
        "CELERY_CACHE_BACKEND",
        "STATIC_ROOT",
        "PYMAP_LOGDIR",
    ]
    custom_settings = {v: os.getenv(v) for v in SETTINGS if os.getenv(v)}

    if len(custom_settings.keys()) == 0:
        return
    for key, value in custom_settings.items():
        if key and value:
            print(f"LOADED {key}={value[:2]}...")
            globals()[key] = value

    # add PYMAP_HOSTNAME to ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS
    hostname = os.getenv("PYMAP_HOSTNAME")
    if hostname:
        ALLOWED_HOSTS.append(hostname)
        CSRF_TRUSTED_ORIGINS.append(f"https://{hostname}")


def check_log_directory() -> str:
    """
    Check if the log directory exists and is readable/writable.
    Return found path taking precedence from Environment->Config file->Default value

    Raises:
        FileNotFoundError: If the log directory does not exist.
        PermissionError: If the log directory is not readable or writable.
    """
    _default = "/var/log/pymap" if DJANGO_ENV == "production" else "pymap_logs"
    print(f"Default logdir: {_default}")
    _env = os.environ.get("PYMAP_LOGDIR", None)
    print(f"Environment variable logdir: {_env}")
    log_directory = _env if _env else PYMAP_SETTINGS.get("PYMAP_LOGDIR", _default)
    print(f"Set logdir as: {log_directory}")
    # Just to ease usage in development
    if DJANGO_ENV == "development":
        Path(PYMAP_LOGDIR).mkdir(parents=True, exist_ok=True)
        if not Path(PYMAP_LOGDIR).exists():
            raise FileNotFoundError(
                errno.ENOENT,
                os.strerror(errno.ENOENT),
                f"The log directory {PYMAP_LOGDIR} does not exist.",
            )
        if not os.access(PYMAP_LOGDIR, os.W_OK) or not os.access(PYMAP_LOGDIR, os.R_OK):
            raise PermissionError(
                f"The log directory {PYMAP_LOGDIR} is not readable/writable."
            )
    return log_directory


def verify_secret_key(secret_key: str | None) -> str:
    """
    Verify the SECRET_KEY is provided and set to an appropriate value.

    Raises:
        ImproperlyConfigured: If SECRET_KEY is missing in production environment.
    """
    if secret_key is None and DJANGO_ENV == "production":
        raise ImproperlyConfigured(
            "You need to provide SECRET_KEY from either the config.json file or a .secret file in the app directory"
        )
    elif secret_key is None:
        secret_key = get_random_secret_key()
        print(f"Generated new secret key {secret_key}")
        return secret_key
    return secret_key


def verify_broker_url(broker_url: str | None) -> None:
    """
    Just verifies the broker url is set does not actually validate if it's properly constructed

    Raises:
        ImproperlyConfigured: if broker_url is None or empty string ""
    """
    if broker_url is None or broker_url == "":
        raise ImproperlyConfigured(
            "you need to define CELERY_BROKER_URL in the config.json"
        )


# Load custom settings, secret file, and env variables, if not testing
if not TESTING:
    custom_settings = load_custom_settings(CONFIG_FILE)
    # Do not insert data if values are missing
    LOGGING.update(custom_settings.get("LOGGING", {}))
    DATABASES.update(custom_settings.get("DATABASES", {}))
    CACHES.update(custom_settings.get("CACHES", {}))
    # Set the defaults to the original values if missing
    ALLOWED_HOSTS = custom_settings.get("ALLOWED_HOSTS", ALLOWED_HOSTS)
    CSRF_TRUSTED_ORIGINS = custom_settings.get(
        "CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS
    )

    # Set broker URL
    broker_conf = custom_settings.get("CELERY_BROKER_URL")
    if broker_conf:
        CELERY_BROKER_URL = build_broker_url(broker_conf)
        # Check broker is set
        try:
            verify_broker_url(CELERY_BROKER_URL)
        except ImproperlyConfigured:
            raise
    else:
        raise ImproperlyConfigured(
            "You need to provide a broker url configuration in the config file"
        )

    # Your app-specific settings
    PYMAP_SETTINGS.update(
        {k: v for k, v in custom_settings.items() if k in ["PYMAP_LOGDIR", "HOSTS"]}
    )

# Load settings from environment variables
load_settings_env()

# We only try to load .secret during production to ease development
if DJANGO_ENV == "production":
    try:
        secret_file = os.environ.get("DJANGO_SECRET_FILE")
        if not secret_file:
            secret_file = ".secret"
        SECRET_KEY = load_key_file(secret_file)
        SECRET_KEY = verify_secret_key(SECRET_KEY)
    except ImproperlyConfigured:
        raise

# Set the same secret key for debug and testing
if DEBUG or TESTING:
    SECRET_KEY = "!!DEBUG_KEY!!"

# Call the check_log_directory function during startup
try:
    PYMAP_LOGDIR = check_log_directory()
except (FileNotFoundError, PermissionError) as e:
    raise ImproperlyConfigured(f"Error checking log directory: {e}")

# Only enable the toolbar when we're in debug mode and we're
# not running tests. Django will change DEBUG to be False for
# tests, so we can't rely on DEBUG alone.
ENABLE_DEBUG_TOOLBAR = DEBUG and not TESTING
if ENABLE_DEBUG_TOOLBAR:
    import socket

    print("Enabling debug toolbar")
    INSTALLED_APPS += [
        "debug_toolbar",
    ]
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    DEBUG_TOOLBAR_CONFIG = {
        "DISABLE_PANELS": [
            "debug_toolbar.panels.redirects.RedirectsPanel",
            # Disable profiling panel due to an issue with Python 3.12:
            # https://github.com/jazzband/django-debug-toolbar/issues/1875
            "debug_toolbar.panels.profiling.ProfilingPanel",
        ],
        "SHOW_TEMPLATE_CONTEXT": True,
    }

    # Discovering docker address
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]
